### ISSUE TITLE
StreamWindow cut off if monitor resolution 1920x1080

### ISSUE THREAD

**Issue by tgreiser** [chromakode/streamwall#14]
A relatively easy fix is to start StreamWindow with frame: false. It makes it a little awkward to exit the program so I think there would need to be a way to trigger app.quit() from the UI/keypress events.

```
diff --git a/src/node/StreamWindow.js b/src/node/StreamWindow.js
index ebaf9f4..49850a8 100644
--- a/src/node/StreamWindow.js
+++ b/src/node/StreamWindow.js
@@ -34,6 +34,7 @@ export default class StreamWindow extends EventEmitter {
       backgroundColor: this.backgroundColor,
       useContentSize: true,
       show: false,
+      frame: false,
     })
     win.removeMenu()
     win.loadURL('about:blank')
```

**Comment by sean1138** [comment]
i haven't been able to figure out how to get at the video elements in the streamwall window (dev tools just gives me the overlay elements) to make the grid responsive/flexible so i'll just leave this here as the basic idea i had in mind:
https://tobiasahlin.com/blog/common-flexbox-patterns/#3x3-grid-constrained-proportions-169

i set `win.resizable = true` in StreamWindow.js just to see if the video grid would resize to match the window size.  for all i know there's good reasons why the video grid is apparently setup with fixed pixel sizes instead of something more flexible?

i'm on a 2560x1600 display so this issue doesn't affect me really but i really like this project... wish i could actually contribute something more useful :/

**Comment by chromakode** [comment]
Thank you both for your energy and desire to contribute! I'm down any time to chat in the Discord and find a project that's the right fit for you.

I'd suggest checking out the "Roadmap" project in the projects tab of this repo -- I've written out some future enhancement ideas in there. The fixed screen size and resolution requirements are definitely a UX issue, and I'd like to see it improved. This initial version is prioritized for streamer use, so the fixed 1080p resolution fits that use case. I'm discovering that some folks like to use Streamwall themselves to consume streams, which is awesome! It could support that use case better without costing the streamer usecase, so I'd love to see improvements there.

In particular, there's this roadmap task which I think covers this: https://github.com/chromakode/streamwall/projects/1#card-40562273

One complexity here comes from the way Electron `BrowserView`s work. They exist outside of the DOM and are positioned explicitly using the [`setBounds main thread API`](https://www.electronjs.org/docs/api/browser-view#viewsetboundsbounds-experimental). The `BrowserView`s are individually separate and exist outside of the DOM, which explains why the video elements don't show up when you're inspecting the window -- you're only a single "overlay" `BrowserView` which renders on top.

It would be possible to position the `BrowserViews` based on the position of the flexbox-layout-ed elements in the overlay document, but I think it might not be worth investing in that complexity at the moment. It'd be necessary to generalize the algorithm Streamwall uses to merge adjacent views together if it's moved away from an NxN grid. Totally doable, but I'm not sure it's worth the effort right now. It'd be more straightforward to calculate the size of each `BrowserView` based on the size of the window. Handling window resizes would be a little bit tricky because you have to reposition each `BrowserView`, but it should be doable! I'd be happy to discuss this more over Discord if you're interested in hacking on it.

**Comment by chromakode** [comment]
I've added configuration options for the window size, and the option to make it frameless: https://github.com/chromakode/streamwall/commit/a0fcc4e8a86207f9cf5ade0dcb5e4e0f7e6de995

I think this is the best bang for buck right now in terms of layout flexibility. For streaming, you typically want a fixed size window, so while dynamic resizing would be useful for folks using Streamwall to watch streams, it's not a high priority for now. I'm going to mark this closed, but am happy to revisit at a later date.
